/* eslint-disable react/no-unescaped-entities */
import { ActivityIcon } from "@/components/activity-icon";

export type ShareFormat = "square" | "story";
export type ShareDesign = "orbit" | "passport" | "passport-v2" | "cover" | "cover-v2" | "cover-v3" | "ticket" | "ticket-v2" | "ledger" | "ledger-v2" | "bento";

type ShareCardPreviewProps = {
  completedQuests: string[];
  consistency: number;
  daysShownUp: number;
  design: ShareDesign;
  format: ShareFormat;
  habitCount: number;
  monthName: string;
  year: number;
};

function serial(monthName: string, year: number, days: number) {
  return `${monthName.slice(0, 3).toUpperCase()}${String(year).slice(-2)}-${String(days).padStart(2, "0")}-ADV`;
}

export function ShareCardPreview({ completedQuests, consistency, daysShownUp, design, format, habitCount, monthName, year }: ShareCardPreviewProps) {
  const isStory = format === "story";
  const visibleQuests = completedQuests.slice(0, isStory ? 4 : 3);
  const shell = `${isStory ? "aspect-[9/16] w-full max-w-[350px]" : "aspect-square w-full max-w-[560px]"} relative overflow-hidden transition-all duration-500`;

  if (design === "passport") return <article aria-label="Rhythm Passport share preview" className={`${shell} rounded-[32px] border-[7px] border-[var(--chart-primary)] bg-[color:color-mix(in_srgb,var(--chart-surface)_86%,var(--chart-blue))] p-5 text-[var(--chart-deep)] shadow-[0_30px_70px_rgba(41,39,28,.28)] sm:p-7`}>
    <div className="absolute inset-2 rounded-[22px] border border-[var(--chart-deep)]/20" />
    <div className="absolute inset-x-0 top-0 h-[42%] bg-[var(--chart-deep)]" />
    <div className="absolute inset-x-0 top-[42%] border-t-2 border-dashed border-[var(--chart-deep)]/20" />
    <div className="absolute -right-16 -top-16 size-52 rounded-full border-[36px] border-white/10" />
    <div className="relative flex h-full flex-col">
      <header className="flex items-start justify-between text-white"><div><p className="text-[8px] font-black uppercase tracking-[.24em] text-[var(--chart-primary)]">Aduvia rhythm passport</p><p className="mt-1 text-[6px] uppercase tracking-[.16em] text-white/45">Proof of presence · not perfection</p></div><span className="rounded-full border border-white/20 px-2 py-1 text-[6px] font-black tracking-[.15em]">{serial(monthName, year, daysShownUp)}</span></header>
      <div className={`${isStory ? "mt-12" : "mt-6"} grid grid-cols-[.72fr_1.28fr] items-center gap-4 text-white`}><div className="relative grid aspect-square place-items-center rounded-full border border-white/15"><div className="absolute inset-2 rounded-full border-[6px] border-[var(--chart-primary)]" style={{ clipPath: `polygon(0 0, 100% 0, 100% ${Math.max(12, consistency)}%, 0 ${Math.max(12, consistency)}%)` }} /><div className="text-center"><p className="text-4xl font-semibold tracking-[-.08em]">{consistency}%</p><p className="text-[6px] uppercase tracking-[.18em] text-white/45">consistent</p></div></div><div><p className="text-[7px] uppercase tracking-[.18em] text-white/40">Month of issue</p><p className="mt-1 text-2xl font-semibold">{monthName} {year}</p><div className="mt-4 grid grid-cols-2 gap-3"><div><p className="text-xl font-semibold text-[var(--chart-primary)]">{daysShownUp}</p><p className="text-[6px] text-white/45">days present</p></div><div><p className="text-xl font-semibold text-[var(--chart-primary)]">{habitCount}</p><p className="text-[6px] text-white/45">active rhythms</p></div></div></div></div>
      <section className={`${isStory ? "mt-10" : "mt-10"} relative flex-1`}><div className="flex items-end justify-between"><div><p className="text-[7px] font-black uppercase tracking-[.2em] text-[var(--chart-ink)]">Monthly visas</p><p className="mt-1 text-xl font-semibold">{completedQuests.length} quests landed</p></div><div className="grid size-12 place-items-center rounded-full border-2 border-[var(--chart-deep)]/25 text-center text-[6px] font-black uppercase leading-3 rotate-[-9deg]">Aduvia<br />verified</div></div><div className="mt-4 space-y-2">{visibleQuests.map((quest, index) => <div className="flex items-center gap-3 border-b border-[var(--chart-deep)]/12 pb-2" key={quest}><span className="grid size-7 shrink-0 place-items-center rounded-full bg-[var(--chart-primary)] text-[10px] font-black">{String(index + 1).padStart(2, "0")}</span><p className="truncate text-[9px] font-bold">{quest}</p></div>)}</div></section>
      <footer className="relative mt-auto flex items-center justify-between border-t border-[var(--chart-deep)]/15 pt-3 text-[6px] uppercase tracking-[.16em] text-[var(--chart-ink)]"><span>Valid for one lived month</span><span>aduvia.app</span></footer>
    </div>
  </article>;

  if (design === "cover") return <article aria-label="Month Cover share preview" className={`${shell} rounded-[10px] bg-[linear-gradient(150deg,var(--chart-primary),color-mix(in_srgb,var(--chart-primary)_58%,var(--chart-surface)))] p-5 text-[var(--chart-deep)] shadow-[14px_14px_0_var(--chart-deep)] sm:p-7`}>
    <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(90deg,transparent 49.5%,currentColor 50%,transparent 50.5%),linear-gradient(transparent 49.5%,currentColor 50%,transparent 50.5%)", backgroundSize: "44px 44px" }} />
    <div className="relative flex h-full flex-col"><header className="flex items-start justify-between border-b-2 border-[var(--chart-deep)] pb-3"><div><p className="text-[8px] font-black uppercase tracking-[.28em]">Aduvia / issue {String(new Date().getMonth() + 1).padStart(2, "0")}</p><p className="mt-1 text-[6px] uppercase tracking-[.14em]">The month in motion</p></div><p className="text-right text-[8px] font-bold uppercase">{monthName}<br />{year}</p></header>
      <div className={`${isStory ? "mt-14" : "mt-6"}`}><p className={`${isStory ? "text-[112px]" : "text-[90px]"} font-black leading-[.72] tracking-[-.11em]`}>{consistency}</p><p className="mt-3 text-[10px] font-black uppercase tracking-[.42em]">percent rhythm</p></div>
      <div className={`${isStory ? "mt-16" : "mt-9"} grid grid-cols-[1fr_auto] gap-5 border-y-2 border-[var(--chart-deep)] py-4`}><p className="text-2xl font-semibold leading-[.9] tracking-[-.05em]">I showed up<br />{daysShownUp} times.</p><div className="flex gap-1">{Array.from({ length: 5 }, (_, index) => <span className={`w-2 rounded-full ${index < Math.ceil(consistency / 20) ? "bg-[var(--chart-deep)]" : "bg-[var(--chart-deep)]/15"}`} key={index} />)}</div></div>
      <section className={`${isStory ? "mt-9" : "mt-6"}`}><p className="text-[7px] font-black uppercase tracking-[.22em]">Quest headlines</p><div className="mt-3 space-y-2">{visibleQuests.length ? visibleQuests.map((quest, index) => <div className="grid grid-cols-[24px_1fr] gap-2" key={quest}><span className="text-[8px] font-black">0{index + 1}</span><p className="truncate border-b border-[var(--chart-deep)]/35 pb-2 text-[9px] font-bold uppercase">{quest}</p></div>) : <p className="text-lg font-semibold">The story is still being written.</p>}</div></section>
      <footer className="mt-auto flex items-end justify-between"><p className="max-w-[160px] text-[7px] font-bold uppercase leading-3 tracking-[.12em]">Small steps became visible proof.</p><p className="text-3xl font-black tracking-[-.08em]">A.</p></footer></div>
  </article>;

  if (design === "ticket") return <article aria-label="Afterglow Ticket share preview" className={`${shell} rounded-[30px] bg-[var(--chart-deep)] p-5 text-white shadow-[0_30px_70px_rgba(20,61,49,.3)] sm:p-7`}>
    <div className="absolute inset-x-0 top-0 h-[38%] bg-[radial-gradient(circle_at_75%_15%,color-mix(in_srgb,var(--chart-rust)_70%,transparent),transparent_44%),linear-gradient(145deg,var(--chart-blue),var(--chart-deep))]" />
    <div className="absolute -left-3 top-[38%] size-6 -translate-y-1/2 rounded-full bg-[var(--soft-tint-a)]" /><div className="absolute -right-3 top-[38%] size-6 -translate-y-1/2 rounded-full bg-[var(--soft-tint-a)]" />
    <div className="absolute inset-x-5 top-[38%] border-t border-dashed border-white/25" />
    <div className="relative flex h-full flex-col"><header className="flex items-start justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.24em] text-[var(--chart-primary)]">Aduvia afterglow</p><p className="mt-1 text-[6px] uppercase tracking-[.16em] text-white/45">Admit one lived month</p></div><p className="text-right text-[7px] font-bold uppercase tracking-[.12em]">{monthName}<br />{year}</p></header>
      <div className={`${isStory ? "mt-16" : "mt-8"} flex items-end justify-between`}><div><p className={`${isStory ? "text-7xl" : "text-6xl"} font-semibold tracking-[-.1em]`}>{consistency}%</p><p className="mt-2 text-[7px] uppercase tracking-[.22em] text-white/45">entry by consistency</p></div><div className="grid size-16 place-items-center rounded-full border border-white/20 text-center"><p className="text-xl font-semibold text-[var(--chart-primary)]">{daysShownUp}<span className="block text-[6px] uppercase tracking-[.12em] text-white/40">days</span></p></div></div>
      <section className={`${isStory ? "mt-20" : "mt-12"}`}><div className="flex justify-between text-[7px] uppercase tracking-[.18em] text-white/40"><span>Monthly set list</span><span>{completedQuests.length} cleared</span></div><div className="mt-4 space-y-3">{visibleQuests.map((quest, index) => <div className="grid grid-cols-[28px_1fr_auto] items-center gap-2" key={quest}><span className="text-[7px] text-[var(--chart-primary)]">A{index + 1}</span><p className="truncate border-b border-white/15 pb-2 text-[9px] font-semibold">{quest}</p><span className="text-[7px] text-white/35">CLEARED</span></div>)}</div></section>
      <footer className="mt-auto flex items-end justify-between"><div className="flex gap-1">{Array.from({length: 12}, (_, i) => <i className={`h-8 w-1 ${i % 3 === 0 ? "bg-[var(--chart-primary)]" : "bg-white/30"}`} key={i} />)}</div><p className="text-right text-[6px] uppercase leading-3 tracking-[.14em] text-white/35">Keep this proof<br />Aduvia {serial(monthName, year, daysShownUp)}</p></footer></div>
  </article>;

  if (design === "ledger") return <article aria-label="Quiet Ledger share preview" className={`${shell} rounded-[24px] border border-[var(--chart-deep)]/15 bg-[var(--chart-surface)] p-5 text-[var(--chart-deep)] shadow-[0_30px_70px_rgba(41,39,28,.2)] sm:p-7`}>
    <div className="absolute inset-0 opacity-35" style={{backgroundImage:"linear-gradient(var(--chart-ink) 1px,transparent 1px)", backgroundSize:"100% 34px"}} />
    <div className="relative flex h-full flex-col"><header className="flex items-start justify-between border-b-2 border-[var(--chart-deep)] pb-4"><div><p className="text-[8px] font-black uppercase tracking-[.24em]">Quiet ledger</p><p className="mt-1 text-[6px] uppercase tracking-[.15em] text-[var(--chart-ink)]">A record of returning</p></div><span className="rounded-full bg-[var(--chart-blue)] px-3 py-1 text-[7px] font-bold text-white">{monthName} {year}</span></header>
      <div className={`${isStory ? "mt-14" : "mt-7"} grid grid-cols-[1fr_auto] items-end gap-4`}><div><p className={`${isStory ? "text-7xl" : "text-6xl"} font-semibold tracking-[-.09em]`}>{daysShownUp}</p><p className="text-[8px] uppercase tracking-[.18em] text-[var(--chart-ink)]">days I returned</p></div><p className="text-3xl font-semibold text-[var(--chart-rust)]">{consistency}%</p></div>
      <div className={`${isStory ? "mt-12" : "mt-7"} grid grid-cols-7 gap-1.5`}>{Array.from({length: 28}, (_, index) => <i className={`aspect-square rounded-[4px] ${index < Math.round(daysShownUp / 31 * 28) ? index % 5 === 0 ? "bg-[var(--chart-rust)]" : "bg-[var(--chart-blue)]" : "bg-[var(--chart-deep)]/8"}`} key={index} />)}</div>
      <section className={`${isStory ? "mt-12" : "mt-7"}`}><p className="text-[7px] font-black uppercase tracking-[.2em] text-[var(--chart-ink)]">Things that became real</p><div className="mt-3 space-y-2">{visibleQuests.map((quest, index) => <div className="flex items-center gap-3 border-b border-[var(--chart-deep)]/15 pb-2" key={quest}><span className="text-[8px] font-black text-[var(--chart-rust)]">{String(index + 1).padStart(2,"0")}</span><p className="truncate text-[9px] font-semibold">{quest}</p></div>)}</div></section>
      <footer className="mt-auto flex justify-between border-t-2 border-[var(--chart-deep)] pt-3 text-[6px] uppercase tracking-[.14em] text-[var(--chart-ink)]"><span>{habitCount} active rhythms</span><span>Signed · Aduvia</span></footer></div>
  </article>;

  if (design === "passport-v2") return <article aria-label="Rhythm Passport share preview" className={`${shell} rounded-[28px] border-[6px] border-[var(--chart-deep)] bg-[var(--chart-surface)] p-5 text-[var(--chart-deep)] shadow-[0_30px_70px_rgba(41,39,28,.24)] sm:p-7`}>
    <div className="absolute inset-2 rounded-[19px] border border-[var(--chart-deep)]/20" />
    <div className="absolute inset-x-0 top-0 h-[46%] bg-[linear-gradient(145deg,var(--chart-blue),var(--chart-deep))]" />
    <div className="absolute right-[-12%] top-[-7%] size-[46%] rounded-full border-[28px] border-white/[.07]" />
    <div className="relative flex h-full flex-col"><header className="flex items-start justify-between text-white"><div><p className="text-[8px] font-black uppercase tracking-[.25em] text-[var(--chart-primary)]">Aduvia rhythm passport</p><p className="mt-1 text-[6px] uppercase tracking-[.14em] text-white/45">Monthly document of presence</p></div><span className="rounded-full border border-white/20 px-2 py-1 text-[6px] font-black tracking-[.12em]">P · ADV</span></header>
      <div className={`${isStory ? "mt-12" : "mt-6"} grid grid-cols-[88px_1fr] gap-4 text-white sm:grid-cols-[108px_1fr]`}><div className="grid aspect-[.78] place-items-center rounded-[18px] border border-white/15 bg-white/[.06]"><div className="relative grid size-16 place-items-center rounded-full border border-white/20"><span className="text-2xl font-semibold">A</span><i className="absolute inset-[-6px] rounded-full border border-dashed border-[var(--chart-primary)]/70" /></div></div><div className="grid grid-cols-2 content-center gap-x-4 gap-y-3"><div className="col-span-2"><p className="text-[6px] uppercase tracking-[.16em] text-white/35">Passport number</p><p className="mt-1 text-sm font-semibold tracking-[.12em]">{serial(monthName, year, daysShownUp)}</p></div><div><p className="text-[6px] uppercase tracking-[.16em] text-white/35">First name</p><p className="mt-1 text-[10px] font-bold uppercase">Aduvia</p></div><div><p className="text-[6px] uppercase tracking-[.16em] text-white/35">Last name</p><p className="mt-1 text-[10px] font-bold uppercase">Member</p></div><div><p className="text-[6px] uppercase tracking-[.16em] text-white/35">Issued</p><p className="mt-1 text-[9px] font-semibold">{monthName} {year}</p></div><div><p className="text-[6px] uppercase tracking-[.16em] text-white/35">Type</p><p className="mt-1 text-[9px] font-semibold">MONTHLY</p></div></div></div>
      <section className={`${isStory ? "mt-12" : "mt-7"} grid grid-cols-[.82fr_1.18fr] items-center gap-5`}><div className="relative grid aspect-square place-items-center rounded-full border-[8px] border-[var(--chart-deep)]/10" style={{background:`conic-gradient(var(--chart-rust) ${consistency * 3.6}deg,transparent 0)`}}><div className="grid size-[72%] place-items-center rounded-full bg-[var(--chart-surface)] text-center"><div><p className="text-3xl font-semibold tracking-[-.08em]">{consistency}%</p><p className="text-[6px] uppercase tracking-[.15em] text-[var(--chart-ink)]">consistent</p></div></div></div><div><div className="grid grid-cols-2 gap-3"><div><p className="text-xl font-semibold text-[var(--chart-rust)]">{daysShownUp}</p><p className="text-[6px] text-[var(--chart-ink)]">days present</p></div><div><p className="text-xl font-semibold text-[var(--chart-rust)]">{habitCount}</p><p className="text-[6px] text-[var(--chart-ink)]">active rhythms</p></div></div><div className="relative mt-4 grid h-16 place-items-center overflow-hidden rounded-xl border border-[var(--chart-deep)]/15"><div className="absolute size-14 rounded-full border-2 border-[var(--chart-rust)]/60" /><div className="absolute size-11 rounded-full border border-dashed border-[var(--chart-rust)]/60" /><p className="relative -rotate-6 text-center text-[6px] font-black uppercase leading-3 tracking-[.12em] text-[var(--chart-rust)]">Aduvia<br />month verified</p></div></div></section>
      <section className={`${isStory ? "mt-8" : "mt-5"}`}><p className="text-[7px] font-black uppercase tracking-[.18em] text-[var(--chart-ink)]">Cleared visas</p><div className="mt-2 space-y-1.5">{visibleQuests.slice(0,isStory ? 3 : 2).map((quest,index)=><div className="flex items-center gap-2 border-b border-[var(--chart-deep)]/12 pb-1.5" key={quest}><span className="text-[7px] font-black text-[var(--chart-rust)]">0{index+1}</span><p className="truncate text-[8px] font-semibold">{quest}</p></div>)}</div></section>
      <footer className="mt-auto border-t border-[var(--chart-deep)]/20 pt-2 font-mono text-[6px] uppercase tracking-[.13em] text-[var(--chart-ink)]"><p>P&lt;ADUVIAMEMBER&lt;&lt;{monthName.toUpperCase().slice(0,6)}{year}&lt;&lt;&lt;</p><p>{serial(monthName,year,daysShownUp)}&lt;{consistency}PC&lt;VALID</p></footer></div>
  </article>;

  if (design === "cover-v2") return <article aria-label="Month Cover share preview" className={`${shell} rounded-[14px] bg-[linear-gradient(145deg,var(--chart-surface)_0_58%,color-mix(in_srgb,var(--chart-blue)_82%,var(--chart-deep))_58%)] p-5 text-[var(--chart-deep)] shadow-[12px_12px_0_color-mix(in_srgb,var(--chart-rust)_70%,var(--chart-deep))] sm:p-7`}><div className="absolute left-[58%] top-0 h-full w-px bg-[var(--chart-deep)]/12" /><div className="relative flex h-full flex-col"><header className="flex justify-between border-b border-[var(--chart-deep)]/25 pb-3 text-[7px] font-black uppercase tracking-[.2em]"><span>Aduvia / monthly issue</span><span>{monthName} {year}</span></header><div className={`${isStory ? "mt-16" : "mt-8"}`}><p className={`${isStory ? "text-[104px]" : "text-[86px]"} font-black leading-[.72] tracking-[-.11em]`}>{consistency}</p><p className="mt-4 text-[9px] font-black uppercase tracking-[.35em] text-[var(--chart-rust)]">a month in rhythm</p></div><div className={`${isStory ? "mt-14" : "mt-8"} grid grid-cols-[1fr_auto] items-end border-y border-[var(--chart-deep)]/25 py-4`}><p className="text-2xl font-semibold leading-none">{daysShownUp} days<br />of returning.</p><span className="text-5xl font-light text-[var(--chart-blue)]">↗</span></div><section className={`${isStory ? "mt-12" : "mt-7"}`}><p className="text-[7px] font-black uppercase tracking-[.18em]">Inside this issue</p><div className="mt-3 space-y-2">{visibleQuests.map((quest,index)=><div className="grid grid-cols-[22px_1fr]" key={quest}><span className="text-[7px] text-[var(--chart-rust)]">0{index+1}</span><p className="truncate border-b border-[var(--chart-deep)]/20 pb-2 text-[9px] font-bold">{quest}</p></div>)}</div></section><footer className="mt-auto flex justify-between text-[6px] uppercase tracking-[.16em] text-[var(--chart-ink)]"><span>Small steps / visible proof</span><span>ADUVIA®</span></footer></div></article>;

  if (design === "ticket-v2") return <article aria-label="Afterglow Ticket share preview" className={`${shell} rounded-[30px] bg-[var(--chart-deep)] p-5 text-white shadow-[0_30px_70px_rgba(20,61,49,.3)] sm:p-7`}><div className="absolute inset-x-0 top-0 h-[34%] bg-[radial-gradient(circle_at_75%_10%,color-mix(in_srgb,var(--chart-rust)_80%,transparent),transparent_43%),linear-gradient(145deg,var(--chart-blue),var(--chart-deep))]" /><div className="absolute -left-3 top-[36%] size-6 rounded-full bg-[var(--soft-tint-a)]" /><div className="absolute -right-3 top-[36%] size-6 rounded-full bg-[var(--soft-tint-a)]" /><div className="absolute inset-x-5 top-[38%] border-t border-dashed border-white/25" /><div className="relative flex h-full flex-col"><header className="flex justify-between"><div><p className="text-[8px] font-black uppercase tracking-[.22em] text-[var(--chart-primary)]">Aduvia afterglow</p><p className="mt-1 text-[6px] uppercase tracking-[.14em] text-white/40">Monthly admission</p></div><p className="text-right text-[7px] font-bold">{serial(monthName,year,daysShownUp)}</p></header><div className={`${isStory ? "mt-16" : "mt-8"} flex items-end justify-between`}><div><p className="text-[7px] uppercase tracking-[.18em] text-white/45">Admit one</p><p className="mt-2 text-4xl font-semibold">{daysShownUp} returns</p></div><p className="text-5xl font-semibold tracking-[-.08em] text-[var(--chart-primary)]">{consistency}%</p></div><section className={`${isStory ? "mt-20" : "mt-14"}`}><div className="grid grid-cols-3 gap-2 rounded-2xl bg-white/[.06] p-3"><div><p className="text-[6px] uppercase text-white/35">Gate</p><p className="mt-1 text-sm font-bold">A{habitCount}</p></div><div><p className="text-[6px] uppercase text-white/35">Date</p><p className="mt-1 text-sm font-bold">{monthName.slice(0,3).toUpperCase()}</p></div><div><p className="text-[6px] uppercase text-white/35">Class</p><p className="mt-1 text-sm font-bold">CALM</p></div></div><p className="mt-6 text-[7px] uppercase tracking-[.18em] text-white/35">Tonight's encore</p><div className="mt-3 space-y-3">{visibleQuests.map((quest,index)=><div className="grid grid-cols-[26px_1fr_auto] gap-2" key={quest}><span className="text-[7px] text-[var(--chart-primary)]">A{index+1}</span><p className="truncate border-b border-white/15 pb-2 text-[9px] font-semibold">{quest}</p><span className="text-[6px] text-white/30">CLEARED</span></div>)}</div></section><footer className="mt-auto flex justify-between"><div className="flex gap-1">{Array.from({length:16},(_,i)=><i className={`h-9 ${i%4===0?"w-1.5 bg-[var(--chart-primary)]":"w-px bg-white/35"}`} key={i}/>)}</div><p className="text-right text-[6px] uppercase leading-3 tracking-[.13em] text-white/35">No expiration<br />Keep the proof</p></footer></div></article>;

  if (design === "ledger-v2") return <article aria-label="Quiet Ledger share preview" className={`${shell} rounded-[24px] bg-[var(--chart-surface)] p-5 text-[var(--chart-deep)] shadow-[0_30px_70px_rgba(41,39,28,.2)] sm:p-7`}><div className="relative flex h-full flex-col"><header className="flex justify-between border-b-2 border-[var(--chart-deep)] pb-3"><div><p className="text-[8px] font-black uppercase tracking-[.22em]">Return log</p><p className="mt-1 text-[6px] uppercase tracking-[.14em] text-[var(--chart-ink)]">A quiet monthly record</p></div><p className="text-right text-[7px] font-bold">{monthName}<br/>{year}</p></header><div className={`${isStory?"mt-14":"mt-8"} grid grid-cols-[1.1fr_.9fr] gap-5`}><div><p className="text-6xl font-semibold tracking-[-.09em]">{daysShownUp}</p><p className="text-[7px] uppercase tracking-[.18em] text-[var(--chart-ink)]">entries made</p></div><div className="grid place-items-center rounded-full border-[7px] border-[var(--chart-blue)]/15 p-2 text-center"><p className="text-2xl font-semibold text-[var(--chart-rust)]">{consistency}%<span className="block text-[6px] uppercase text-[var(--chart-ink)]">follow-through</span></p></div></div><div className={`${isStory?"mt-12":"mt-8"} grid grid-cols-7 gap-1.5`}>{Array.from({length:28},(_,i)=><div className={`grid aspect-square place-items-center rounded-md text-[6px] ${i<Math.round(daysShownUp/31*28)?"bg-[var(--chart-blue)] text-white":"bg-[var(--chart-deep)]/[.06] text-[var(--chart-ink)]/40"}`} key={i}>{i+1}</div>)}</div><section className={`${isStory?"mt-12":"mt-8"}`}><p className="text-[7px] font-black uppercase tracking-[.18em] text-[var(--chart-rust)]">What moved forward</p><div className="mt-3 space-y-2">{visibleQuests.map((q,i)=><div className="grid grid-cols-[20px_1fr]" key={q}><span className="text-[7px] font-black">0{i+1}</span><p className="truncate border-b border-[var(--chart-deep)]/15 pb-2 text-[9px] font-semibold">{q}</p></div>)}</div></section><footer className="mt-auto flex justify-between border-t-2 border-[var(--chart-deep)] pt-2 text-[6px] uppercase tracking-[.15em] text-[var(--chart-ink)]"><span>{habitCount} rhythms observed</span><span>Aduvia logbook</span></footer></div></article>;

  if (design === "bento") return <article aria-label="Insight Bento share preview" className={`${shell} rounded-[32px] bg-[var(--chart-deep)] p-4 text-white shadow-[0_30px_70px_rgba(20,61,49,.3)] sm:p-6`}><div className="relative flex h-full flex-col"><header className="flex justify-between px-1"><div><p className="text-[8px] font-black uppercase tracking-[.22em] text-[var(--chart-primary)]">Aduvia month signal</p><p className="mt-1 text-[6px] uppercase tracking-[.14em] text-white/40">Four views · one quiet story</p></div><p className="text-right text-[7px] font-bold uppercase">{monthName}<br/>{year}</p></header><div className={`${isStory?"mt-8 grid-cols-1":"mt-5 grid-cols-2"} grid flex-1 gap-2`}><section className="grid min-h-0 place-items-center rounded-[22px] bg-white/[.07] p-3"><div className="relative grid size-24 place-items-center rounded-full p-[7px]" style={{background:`conic-gradient(var(--chart-primary) ${consistency*3.6}deg,rgba(255,255,255,.1) 0)`}}><div className="grid size-full place-items-center rounded-full bg-[var(--chart-deep)] text-center"><p className="text-2xl font-semibold">{consistency}%<span className="block text-[6px] uppercase text-white/40">consistency</span></p></div></div></section><section className="rounded-[22px] bg-[var(--chart-surface)] p-3 text-[var(--chart-deep)]"><p className="text-[6px] font-black uppercase tracking-[.15em] text-[var(--chart-ink)]">Week rhythm</p><div className="mt-4 flex h-20 items-end gap-1.5">{[72,58,86,48,78,42,64].map((v,i)=><i className="flex-1 rounded-t-md bg-[var(--chart-blue)]" key={i} style={{height:`${v}%`,opacity:.55+i*.06}}/>)}</div><div className="mt-2 flex justify-between text-[5px] text-[var(--chart-ink)]"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div></section><section className="rounded-[22px] bg-[color:color-mix(in_srgb,var(--chart-rust)_72%,var(--chart-deep))] p-3"><p className="text-[6px] font-black uppercase tracking-[.15em] text-white/55">Days in motion</p><p className="mt-2 text-4xl font-semibold">{daysShownUp}</p><div className="mt-3 grid grid-cols-7 gap-1">{Array.from({length:28},(_,i)=><i className={`aspect-square rounded-[3px] ${i<Math.round(daysShownUp/31*28)?"bg-[var(--chart-primary)]":"bg-white/12"}`} key={i}/>)}</div></section><section className="rounded-[22px] bg-[var(--chart-blue)] p-3"><p className="text-[6px] font-black uppercase tracking-[.15em] text-white/55">Quests landed</p><p className="mt-2 text-4xl font-semibold">{completedQuests.length}</p><div className="mt-3 space-y-1.5">{visibleQuests.slice(0,3).map((q,i)=><p className="truncate border-b border-white/15 pb-1.5 text-[7px] font-semibold" key={q}>0{i+1} · {q}</p>)}</div></section></div><footer className="mt-3 flex justify-between px-1 text-[6px] uppercase tracking-[.14em] text-white/35"><span>Personal insight atlas</span><span>aduvia.app</span></footer></div></article>;

  if (design === "cover-v3") return <article aria-label="Month Cover share preview" className={`${shell} rounded-[20px] bg-[linear-gradient(145deg,color-mix(in_srgb,var(--chart-surface)_88%,var(--chart-blue)),var(--chart-surface))] p-5 text-[var(--chart-deep)] shadow-[11px_11px_0_var(--chart-deep)] sm:p-7`}>
    <div className="absolute -right-[16%] -top-[15%] size-[58%] rounded-full border-[1px] border-[var(--chart-rust)]/25" /><div className="absolute -right-[5%] -top-[4%] size-[36%] rounded-full border-[1px] border-[var(--chart-rust)]/30" /><div className="absolute right-[5%] top-[6%] size-[17%] rounded-full border-[1px] border-[var(--chart-rust)]/35" />
    <div className="absolute bottom-0 right-0 h-[34%] w-[42%] bg-[radial-gradient(circle_at_100%_100%,color-mix(in_srgb,var(--chart-blue)_20%,transparent),transparent_70%)]" />
    <div className="relative flex h-full flex-col"><header className="flex justify-between border-b border-[var(--chart-deep)]/40 pb-3"><div><p className="text-[8px] font-black uppercase tracking-[.22em]">Aduvia / issue {String(new Date().getMonth()+1).padStart(2,"0")}</p><p className="mt-1 text-[6px] uppercase tracking-[.14em] text-[var(--chart-ink)]">The month in motion</p></div><p className="text-right text-[7px] font-bold uppercase">{monthName}<br />{year}</p></header>
      <div className={`${isStory ? "mt-12" : "mt-6"} grid grid-cols-[1fr_auto] items-end gap-6`}><div className="w-fit text-center"><p className={`${isStory ? "text-[5.5rem]" : "text-9xl"} font-black leading-[.82] tracking-[-.09em]`}>{consistency}</p><p className="mt-4 text-[6px] font-black uppercase tracking-[.2em] text-[var(--chart-rust)]">percent rhythm</p></div><div className="grid min-w-[92px] gap-4 border-l border-[var(--chart-deep)]/20 pl-4 text-center"><div><p className="text-3xl font-black leading-none tracking-[-.07em]">{daysShownUp}</p><p className="mt-2 text-[6px] font-black uppercase tracking-[.16em] text-[var(--chart-ink)]">days in orbit</p></div><div><p className="text-3xl font-black leading-none tracking-[-.07em]">{habitCount}</p><p className="mt-2 text-[6px] font-black uppercase tracking-[.16em] text-[var(--chart-ink)]">daily rituals</p></div></div></div>
      <div className={`${isStory ? "mt-8" : "mt-4"} flex items-end justify-between border-y border-[var(--chart-deep)]/35 py-3`}><div><p className="text-[7px] font-black uppercase tracking-[.18em] text-[var(--chart-rust)]">Return note</p><p className="mt-2 text-2xl font-semibold leading-[.92]">I showed up<br />{daysShownUp} times.</p></div><div className="flex h-14 items-end gap-1.5">{[48,74,58,92,68].map((value,index)=><i className="w-2 rounded-full bg-[var(--chart-blue)]" key={index} style={{height:`${value}%`,opacity:.48+index*.1}} />)}</div></div>
      <section className={`${isStory ? "mt-10" : "mt-6"}`}><div className="flex items-end justify-between"><p className="text-[7px] font-black uppercase tracking-[.19em]">Quest headlines</p><p className="text-[7px] font-bold uppercase tracking-[.12em] text-[var(--chart-rust)]">{completedQuests.length} completed</p></div><div className="mt-3 space-y-2">{visibleQuests.map((quest)=><div className="grid grid-cols-[34px_1fr] items-center gap-2" key={quest}><span className="grid size-7 place-items-center rounded-full border border-[var(--chart-rust)]/35 bg-[var(--chart-rust)]/10 text-[var(--chart-rust)]"><ActivityIcon activity={quest} className="size-[17px]" /></span><p className="truncate border-b border-[var(--chart-deep)]/20 pb-2 text-[8px] font-bold uppercase">{quest}</p></div>)}</div></section>
      <footer className="mt-auto flex items-end justify-between text-[6px] uppercase tracking-[.15em] text-[var(--chart-ink)]"><span>Small steps became visible proof.</span><span className="text-2xl font-black tracking-[-.08em] text-[var(--chart-deep)]">A.</span></footer></div>
  </article>;

  return <article aria-label="Orbit Signal share preview" className={`${shell} rounded-[38px] bg-[linear-gradient(145deg,var(--chart-deep),color-mix(in_srgb,var(--chart-deep)_78%,var(--chart-green)))] p-6 text-white shadow-[0_30px_70px_rgba(20,61,49,.28)] sm:p-8`}>
    <div className="absolute inset-0 opacity-30" style={{ backgroundImage: "repeating-radial-gradient(ellipse at 25% 10%, transparent 0 15px, rgba(255,255,255,.055) 16px 17px)" }} />
    <div className="relative flex h-full flex-col"><header className="flex justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.21em] text-[var(--chart-primary)]">Aduvia</p><p className="text-[7px] uppercase tracking-[.14em] text-white/40">Monthly constellation</p></div><p className="text-right text-[8px] uppercase tracking-[.14em]">{monthName}<br /><span className="text-white/35">{year}</span></p></header>
      <div className={`${isStory ? "mt-14" : "mt-6"} relative grid flex-1 place-items-center`}><div className="absolute h-[36%] w-[78%] rotate-6 rounded-[50%] border border-white/15" /><div className="absolute h-[50%] w-[92%] -rotate-6 rounded-[50%] border border-white/12" /><div className="absolute h-[24%] w-[58%] -rotate-12 rounded-[50%] border border-white/18" />{Array.from({ length: 11 }, (_, index) => <i className="absolute size-1.5 rounded-full bg-[var(--chart-primary)] shadow-[0_0_10px_var(--chart-primary)]" key={index} style={{ left: `${12 + (index * 31) % 78}%`, top: `${18 + (index * 47) % 64}%` }} />)}<div className="relative grid size-28 place-items-center rounded-full bg-[var(--chart-deep)] p-[7px]" style={{ background: `conic-gradient(var(--chart-primary) ${consistency * 3.6}deg, rgba(255,255,255,.12) 0deg)` }}><div className="grid size-full place-items-center rounded-full bg-[var(--chart-deep)] text-center"><div><p className="text-3xl font-semibold tracking-[-.07em]">{consistency}%</p><p className="text-[6px] uppercase tracking-[.16em] text-white/45">rhythm signal</p></div></div></div></div>
      <section className="relative rounded-[22px] bg-[var(--chart-surface)] p-4 text-[var(--soft-ink)]"><div className="grid grid-cols-3 gap-2"><div><p className="text-2xl font-semibold">{daysShownUp}</p><p className="text-[7px] text-[var(--chart-ink)]">days in orbit</p></div><div><p className="text-2xl font-semibold">{habitCount}</p><p className="text-[7px] text-[var(--chart-ink)]">daily rituals</p></div><div><p className="text-2xl font-semibold">{completedQuests.length}</p><p className="text-[7px] text-[var(--chart-ink)]">quests landed</p></div></div></section>
      <footer className="relative mt-3 flex justify-between text-[6px] uppercase tracking-[.14em] text-white/35"><span>Issued {monthName} {year}</span><span>Visible proof</span></footer></div>
  </article>;
}
